#!/bin/bash
# Script for running simulation

echo "run RSSALib"

java -d64 -Xms4g -Xmx4g -cp "./dist/RSSALib.jar:./dist/lib/*.*" run.cmd.CMDSim_DSMTS_1

cp \(Data\)RSSA_00001-sbml-l3v1_*.txt DSMTS_1/data
cp \(Perf\)RSSA_00001-sbml-l3v1_*.* DSMTS_1/performance

rm \(Data\)RSSA_00001-sbml-l3v1_*.txt 
rm \(Perf\)RSSA_00001-sbml-l3v1_*.* 

echo "finish"

