#!/bin/bash
# Script for running simulation

echo "run RSSALib"

java -d64 -Xms4g -Xmx4g -cp "./dist/RSSALib.jar:./dist/lib/*.*" run.cmd.CMDSim_DSMTS_2

cp \(Data\)RSSA_00020-sbml-l3v1_*.txt DSMTS_2/data
cp \(Perf\)RSSA_00020-sbml-l3v1_*.* DSMTS_2/performance

rm \(Data\)RSSA_00020-sbml-l3v1_*.txt 
rm \(Perf\)RSSA_00020-sbml-l3v1_*.* 

echo "finish"

